const ejerciciosTotales = [{id:1, parte:"Pectoral", ejercicio:"Press Plano", imagen:"imag1.jpg"},
                          {id:2, parte:"Pectoral", ejercicio:"Press Inclinado", imagen:"imag1.jpg"},
                          {id:3, parte:"Pectoral", ejercicio:"Press Declinado", imagen:"imag1.jpg"},
                          {id:4, parte:"Pectoral", ejercicio:"Press Plano con Mancuernas", imagen:"imag1.jpg"},
                          {id:5, parte:"Pectoral", ejercicio:"Press Inclinado con Mancuernas", imagen:"imag1.jpg"},
                          {id:6, parte:"Pectoral", ejercicio:"Press Declinado con Mancuernas", imagen:"imag1.jpg"},
                          {id:7, parte:"Pectoral", ejercicio:"Apertura Plana", imagen:"imag1.jpg"},
                          {id:8, parte:"Pectoral", ejercicio:"Apertura Inclinada", imagen:"imag1.jpg"},
                          {id:9, parte:"Pectoral", ejercicio:"Apertura Declinada", imagen:"imag1.jpg"},
                          {id:10, parte:"Pectoral", ejercicio:"Peck Deck", imagen:"imag1.jpg"},
                          {id:11, parte:"Pectoral", ejercicio:"Cruces con Polea Baja", imagen:"imag1.jpg"},
                          {id:12, parte:"Pectoral", ejercicio:"Cruces con Polea Alta", imagen:"imag1.jpg"},
                          {id:13, parte:"Pectoral", ejercicio:"Fondos en Paralelas", imagen:"imag1.jpg"},
                          {id:14, parte:"Pectoral", ejercicio:"Flexiones de brazo", imagen:"imag1.jpg"},
                          {id:15, parte:"Pectoral", ejercicio:"Mancuerna al pectoral", imagen:"imag1.jpg"},
                          {id:16, parte:"Espalda", ejercicio:"Remo bajo con polea", imagen:"imag1.jpg"},
                          {id:17, parte:"Espalda", ejercicio:"Remo con Barra", imagen:"imag1.jpg"},
                          {id:18, parte:"Espalda", ejercicio:"Remo 1 Brazo", imagen:"imag1.jpg"},
                          {id:19, parte:"Espalda", ejercicio:"Remo T", imagen:"imag1.jpg"},
                          {id:20, parte:"Espalda", ejercicio:"Remo Caballo", imagen:"imag1.jpg"},
                          {id:21, parte:"Espalda", ejercicio:"Dominadas", imagen:"imag1.jpg"},
                          {id:22, parte:"Espalda", ejercicio:"Tirones con polea", imagen:"imag1.jpg"},
                          {id:23, parte:"Espalda", ejercicio:"Tirones con Hummer", imagen:"imag1.jpg"},
                          {id:24, parte:"Espalda", ejercicio:"Pull Over con mancuerna", imagen:"imag1.jpg"},
                          {id:25, parte:"Espalda", ejercicio:"Pull Over con polea ", imagen:"imag1.jpg"},
                          {id:26, parte:"Espalda", ejercicio:"Remo bajo con polea", imagen:"imag1.jpg"},
                          {id:27, parte:"Hombros", ejercicio:"Press Militar con Barra", imagen:"imag1.jpg"},
                          {id:28, parte:"Hombros", ejercicio:"Press Militar con Mancuerna", imagen:"imag1.jpg"},
                          {id:29, parte:"Hombros", ejercicio:"Press Militar en MultiPower", imagen:"imag1.jpg"},
                          {id:30, parte:"Hombros", ejercicio:"Press Arnold", imagen:"imag1.jpg"},
                          {id:31, parte:"Hombros", ejercicio:"Vuelos Laterales", imagen:"imag1.jpg"},
                          {id:32, parte:"Hombros", ejercicio:"Vuelos Frontales", imagen:"imag1.jpg"},
                          {id:33, parte:"Hombros", ejercicio:"Vuelos Frontales con Barra", imagen:"imag1.jpg"},
                          {id:34, parte:"Hombros", ejercicio:"Vuelos Frontales con Polea", imagen:"imag1.jpg"},
                          {id:35, parte:"Hombros", ejercicio:"Vuelos Posteriores", imagen:"imag1.jpg"},
                          {id:36, parte:"Hombros", ejercicio:"Posteriores con Soga", imagen:"imag1.jpg"},
                          {id:37, parte:"Biceps", ejercicio:"Curl con Barra", imagen:"imag1.jpg"},
                          {id:38, parte:"Biceps", ejercicio:"Curl con Mancuerna", imagen:"imag1.jpg"},
                          {id:39, parte:"Biceps", ejercicio:"Curl 45 grados", imagen:"imag1.jpg"},
                          {id:40, parte:"Biceps", ejercicio:"Curl Scott", imagen:"imag1.jpg"},
                          {id:41, parte:"Biceps", ejercicio:"Curl Polea", imagen:"imag1.jpg"},                    
                          {id:42, parte:"Biceps", ejercicio:"Curl Concentrado", imagen:"imag1.jpg"},                    
                          {id:43, parte:"Biceps", ejercicio:"Curl Alternado", imagen:"imag1.jpg"},                    
                          {id:44, parte:"Biceps", ejercicio:"Martillo", imagen:"imag1.jpg"},
                          {id:45, parte:"Biceps", ejercicio:"Braquial con barra", imagen:"imag1.jpg"},
                          {id:46, parte:"Triceps", ejercicio:"Empujes", imagen:"imag1.jpg"},
                          {id:47, parte:"Triceps", ejercicio:"Fondos entre bancos", imagen:"imag1.jpg"},
                          {id:48, parte:"Triceps", ejercicio:"Frances con barra", imagen:"imag1.jpg"},
                          {id:49, parte:"Triceps", ejercicio:"Frances 1 Brazo", imagen:"imag1.jpg"},
                          {id:50, parte:"Triceps", ejercicio:"Frances con Mancuernas", imagen:"imag1.jpg"},
                          {id:51, parte:"Triceps", ejercicio:"Frances con Soga", imagen:"imag1.jpg"},
                          {id:52, parte:"Triceps", ejercicio:"Extension con Polea", imagen:"imag1.jpg"},
                          {id:53, parte:"Piernas", ejercicio:"Sentadillas", imagen:"imag1.jpg"},
                          {id:54, parte:"Piernas", ejercicio:"Sentadillas Sumo", imagen:"imag1.jpg"},
                          {id:55, parte:"Piernas", ejercicio:"Sentadillas Sissy", imagen:"imag1.jpg"},
                          {id:56, parte:"Piernas", ejercicio:"Estocadas", imagen:"imag1.jpg"},
                          {id:57, parte:"Piernas", ejercicio:"Estocadas para atras", imagen:"imag1.jpg"},
                          {id:58, parte:"Piernas", ejercicio:"Prensa 45", imagen:"imag1.jpg"},
                          {id:59, parte:"Piernas", ejercicio:"Sillon de Cuadriceps", imagen:"imag1.jpg"},
                          {id:60, parte:"Piernas", ejercicio:"Camilla Izquiotibiales", imagen:"imag1.jpg"},
                          {id:61, parte:"Piernas", ejercicio:"Gemelos de Pie", imagen:"imag1.jpg"},
                          {id:62, parte:"Piernas", ejercicio:"Gemelos en Maquina", imagen:"imag1.jpg"},
                          {id:63, parte:"Piernas", ejercicio:"Prensa 45", imagen:"imag1.jpg"},
                          {id:64, parte:"Piernas", ejercicio:"Hack", imagen:"imag1.jpg"},
                          {id:65, parte:"Piernas", ejercicio:"Hack Invertido", imagen:"imag1.jpg"},
                          {id:66, parte:"Piernas", ejercicio:"Peso Muerto", imagen:"imag1.jpg"},
                          {id:67, parte:"Piernas", ejercicio:"Peso Muerto 1 pie", imagen:"imag1.jpg"},
                          {id:68, parte:"Piernas", ejercicio:"Puentes", imagen:"imag1.jpg"},
                          {id:69, parte:"Piernas", ejercicio:"Patada de Gluteos", imagen:"imag1.jpg"},
                          {id:70, parte:"Piernas", ejercicio:"Soleo Sentado", imagen:"imag1.jpg"},
                          {id:71, parte:"Abdominales", ejercicio:"Crunch con carga", imagen:"imag1.jpg"},
                          {id:72, parte:"Abdominales", ejercicio:"Crunch Oblicuo", imagen:"imag1.jpg"},
                          {id:73, parte:"Abdominales", ejercicio:"Hips", imagen:"imag1.jpg"},]


                          
  function guardarEjerciciosTotalesLS(ejerciciosTotales){
    localStorage.setItem("ejercicios", JSON.stringify(ejerciciosTotales));

  }

  function cargarEjerciciosLS(){
    return JSON.parse(localStorage.getItem("ejercicios"))
  }
